<a href="https://colab.research.google.com/github/datasci-rahul/personal/blob/main/EDX_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# System Overview

- In this course recommendation system, content-based similarity filtering based on the course tags which the users either watch or search is being used. 

- The dataset used is of the [EDX Courses Dataset](https://www.kaggle.com/datasets/imuhammad/edx-courses) which contains over 900 courses!

Another approach can be collabrative filtering, which is not used in this notebook. An advance approach can be using both these approach in a hybrid mode.,

# Importing Dependencies

In [69]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Dependencies Imported

In [70]:
data = pd.read_csv("edx_courses.csv")
data.head(5)

,title,summary,n_enrolled,course_type,institution,instructors,Level,subject,language,subtitles,course_effort,course_length,price,course_description,course_syllabus,course_url
0,How to Learn Online,Learn essential strategies for successful onli...,"124,980",Self-paced on your time,edX,Nina Huntemann-Robyn Belair-Ben Piscopo,Introductory,Education & Teacher Training,English,English,2–3 hours per week,2 Weeks,FREE-Add a Verified Certificate for $49 USD,"Designed for those who are new to elearning, t...",Welcome - We start with opportunities to meet ...,https://www.edx.org/course/how-to-learn-online
1,Programming for Everybody (Getting Started wit...,"This course is a ""no prerequisite"" introductio...","293,864",Self-paced on your time,The University of Michigan,Charles Severance,Introductory,Computer Science,English,English,2–4 hours per week,7 Weeks,FREE-Add a Verified Certificate for $49 USD,This course aims to teach everyone the basics ...,NaN,https://www.edx.org/course/programming-for-eve...
2,CS50's Introduction to Computer Science,An introduction to the intellectual enterprise...,"2,442,271",Self-paced on your time,Harvard University,David J. Malan-Doug Lloyd-Brian Yu,Introductory,Computer Science,English,English,6–18 hours per week,12 Weeks,FREE-Add a Verified Certificate for $90 USD,"This is CS50x , Harvard University's introduct...",NaN,https://www.edx.org/course/cs50s-introduction-...
3,The Analytics Edge,"Through inspiring examples and stories, discov...","129,555",Instructor-led on a course schedule,Massachusetts Institute of Technology,Dimitris Bertsimas-Allison O'Hair-John Silberh...,Intermediate,Data Analysis & Statistics,English,English,10–15 hours per week,13 Weeks,FREE-Add a Verified Certificate for $199 USD,"In the last decade, the amount of data availab...",NaN,https://www.edx.org/course/the-analytics-edge
4,Marketing Analytics: Marketing Measurement Str...,This course is part of a MicroMasters® Program,"81,140",Self-paced on your time,"University of California, Berkeley",Stephan Sorger,Introductory,Computer Science,English,English,5–7 hours per week,4 Weeks,FREE-Add a Verified Certificate for $249 USD,Begin your journey in a new career in marketin...,NaN,https://www.edx.org/course/marketing-analytics...

# Basic Data Analysis

In [71]:
data.shape

(975, 16)

In [72]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               975 non-null    object
 1   summary             922 non-null    object
 2   n_enrolled          855 non-null    object
 3   course_type         975 non-null    object
 4   institution         975 non-null    object
 5   instructors         972 non-null    object
 6   Level               975 non-null    object
 7   subject             975 non-null    object
 8   language            975 non-null    object
 9   subtitles           972 non-null    object
 10  course_effort       975 non-null    object
 11  course_length       975 non-null    object
 12  price               975 non-null    object
 13  course_description  935 non-null    object
 14  course_syllabus     417 non-null    object
 15  course_url          975 non-null    object
dtypes: object(16)
memory usage: 122.0+ KB

In [73]:
data.isnull().sum() #no value is missing

title                   0
summary                53
n_enrolled            120
course_type             0
institution             0
instructors             3
Level                   0
subject                 0
language                0
subtitles               3
course_effort           0
course_length           0
price                   0
course_description     40
course_syllabus       558
course_url              0
dtype: int64

In [74]:
data.dropna()

,title,summary,n_enrolled,course_type,institution,instructors,Level,subject,language,subtitles,course_effort,course_length,price,course_description,course_syllabus,course_url
0,How to Learn Online,Learn essential strategies for successful onli...,"124,980",Self-paced on your time,edX,Nina Huntemann-Robyn Belair-Ben Piscopo,Introductory,Education & Teacher Training,English,English,2–3 hours per week,2 Weeks,FREE-Add a Verified Certificate for $49 USD,"Designed for those who are new to elearning, t...",Welcome - We start with opportunities to meet ...,https://www.edx.org/course/how-to-learn-online
6,Leading High-Performing Teams,"Learn how to motivate, engage and empower peop...","32,847",Self-paced on your time,The University of Queensland,Tyler G. Okimoto,Intermediate,Communication,English,English,8–10 hours per week,10 Weeks,FREE-Add a Verified Certificate for $5 USD,This course will blend business theory and rea...,MODULE 1: INTRODUCTION TO TEAMS\nFocuses on re...,https://www.edx.org/course/leading-high-perfor...
8,"Managing Study, Stress and Mental Health at Un...",Develop a clearer understanding of what mental...,"23,061",Self-paced on your time,Curtin University,Ben Milbourn-Craig Thompson-Sonya Girdler-Fran...,Introductory,Health & Safety,English,English,1–3 hours per week,2 Weeks,FREE-Add a Verified Certificate for $49 USD,This short course is a German-Australian colla...,Module 1: Mental fitnessBy the end of this mod...,https://www.edx.org/course/managing-study-stre...
9,Six Sigma: Define and Measure,An introduction to the Six Sigma methodology a...,"92,411",Self-paced on your time,Technische Universität München,Martin Grunow-Holly Ott,Introductory,Business & Management,English,English,3–4 hours per week,8 Weeks,FREE-Add a Verified Certificate for $99 USD,Understand the background and meaning of Six S...,Week 1: Six Sigma Introduction\nIntroduction t...,https://www.edx.org/course/six-sigma-define-an...
10,Fat Chance: Probability from the Ground Up,Increase your quantitative reasoning skills th...,"66,835",Self-paced on your time,Harvard University,Benedict Gross-Joseph Harris-Emily Riehl,Introductory,Math,English,English,3–5 hours per week,7 Weeks,FREE-Add a Verified Certificate for $49 USD,Created specifically for those who are new to ...,1 Basic Counting2 Advanced Counting3 Basic Pro...,https://www.edx.org/course/fat-chance-probabil...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961,Sustainable Food Systems: A Mediterranean Pers...,"How do we produce more, better quality, and sa...","6,480",Self-paced on your time,SDG Academy,Jeffrey D. Sachs-Alessio Cavicchi-Sonia Massar...,Intermediate,Food & Nutrition,English,"English, Français, Italiano",2–4 hours per week,10 Weeks,FREE-Add a Verified Certificate for $49 USD,The Mediterranean region is one of the most bi...,PrologueModule 1: The Mediterranean challenges...,https://www.edx.org/course/sustainable-food-sy...
963,Using GPUs to Scale and Speed-up Deep Learning,Training complex deep learning models with lar...,"9,294",Self-paced on your time,IBM,Saeed Aghabozorgi,Intermediate,Data Analysis & Statistics,English,English,2–4 hours per week,5 Weeks,FREE-Add a Verified Certificate for $99 USD,Training acomplex deep learning model with a v...,Module 1 – Quick review of Deep LearningIntro ...,https://www.edx.org/course/using-gpus-to-scale...
966,Introducción a las ondas gravitacionales,"En este curso, junto con la Dra. Gabriela Gonz...","8,657",Self-paced on your time,Universidad Nacional de Córdoba,Gabriela González,Introductory,Science,Español,"English, Español",5–7 hours per week,4 Weeks,FREE-Add a Verified Certificate for $50 USD,En este curso conocerás sobre las ondas gravit...,Introducción: En este curso vamos a hablar de ...,https://www.edx.org/course/introduccion-a-las-...
972,Computational Neuroscience: Neuronal Dynamics ...,This course explains the mathematical and comp...,"11,246",Self-paced on your time,École polytechnique fédérale de Lausanne,Wulfram Gerstner,Advanced,Biology & Life Sciences,English,English,4–6 hours per week,6 Weeks,FREE-Add a Verified Certificate for $139 USD,What happens in your brain when you make a dec...,Textbook: Neuronal Dynamics - from single neur...,https://www.edx.org/course/computational-neuro...
973,Cities and the Challenge of Sustainable Develo...,What is a sustainable city? Learn the basics h...,"8,775",Self-paced on your time,SDG Academy,Jeffrey D. Sachs,Introductory,Environmental Studies,English,English,1–2 hours per week,1 Weeks,FREE-Add a Verified Certificate for $25 USD,"According to the United Nations, urbanization ...",Module 1: Introduction to the SDGsProfessor Je...,https://www.edx.org/course/cities-and-the-chal...

In [75]:
data['Level'].value_counts()

Introductory    621
Intermediate    267
Advanced         87
Name: Level, dtype: int64

In [76]:
data['course_length'].value_counts()

4 Weeks     194
6 Weeks     187
5 Weeks     148
7 Weeks      92
8 Weeks      84
10 Weeks     83
12 Weeks     36
3 Weeks      35
2 Weeks      20
9 Weeks      20
15 Weeks     18
14 Weeks     17
16 Weeks     14
1 Weeks       8
11 Weeks      7
13 Weeks      7
18 Weeks      4
17 Weeks      1
Name: course_length, dtype: int64

In [77]:
data['institution'].value_counts()

Harvard University                                                    104
Universitat Politècnica de Valencia                                    47
Massachusetts Institute of Technology                                  41
Delft University of Technology                                         30
IBM                                                                    30
                                                                     ...
The University of Tokyo                                                 1
Educational Testing Service                                             1
The National University of Singapore                                    1
University of Oxford                                                    1
University of Maryland Global Campus-University System of Maryland      1
Name: institution, Length: 111, dtype: int64

In [78]:
data['title']

0                                    How to Learn Online
1      Programming for Everybody (Getting Started wit...
2                CS50's Introduction to Computer Science
3                                     The Analytics Edge
4      Marketing Analytics: Marketing Measurement Str...
                             ...
970    Leaders in Citizen Security and Justice Manage...
971                Pattern Studying and Making | 图案审美与创作
972    Computational Neuroscience: Neuronal Dynamics ...
973    Cities and the Challenge of Sustainable Develo...
974                        MathTrackX: Special Functions
Name: title, Length: 975, dtype: object

# Required Columns for System

#### Important columns to be used in recommendation system : 

- Course Name : Names of the courses
- Course Description : Similar courses may have similar course description
- Skills : Users may want to see courses based on same skills
- Difficulty Level : Similar courses as per difficulty level 

#### Columns not used for the recommendation system :

- Course Ratings : Numerical Column; Ratings can sometimes become a biased factor and distribution is not even
- University : Same university might offer multiple courses in different domains which the user might not want to see
- Course URL : No significance in the recommendation system

In [79]:
data = data[['title','Level','course_description','subject']]

In [80]:
data.head(5)

,title,Level,course_description,subject
0,How to Learn Online,Introductory,"Designed for those who are new to elearning, t...",Education & Teacher Training
1,Programming for Everybody (Getting Started wit...,Introductory,This course aims to teach everyone the basics ...,Computer Science
2,CS50's Introduction to Computer Science,Introductory,"This is CS50x , Harvard University's introduct...",Computer Science
3,The Analytics Edge,Intermediate,"In the last decade, the amount of data availab...",Data Analysis & Statistics
4,Marketing Analytics: Marketing Measurement Str...,Introductory,Begin your journey in a new career in marketin...,Computer Science

# Data Pre-Processing

An important part of the process is to pre-process the data into usable format for the recommendation system

In [81]:
# Removing spaces between the words (Lambda funtions can be used as well)

data['title'] = data['title'].str.replace(' ',',')
data['title'] = data['title'].str.replace(',,',',')
data['title'] = data['title'].str.replace(':','')
data['course_description'] = data['course_description'].str.replace(' ',',')
data['course_description'] = data['course_description'].str.replace(',,',',')
data['course_description'] = data['course_description'].str.replace('_','')
data['course_description'] = data['course_description'].str.replace(':','')
data['course_description'] = data['course_description'].str.replace('(','')
data['course_description'] = data['course_description'].str.replace(')','')

#removing paranthesis from skills columns 
data['subject'] = data['subject'].str.replace('(','')
data['subject'] = data['subject'].str.replace(')','')

<ipython-input-81-024d722643da>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['title'] = data['title'].str.replace(' ',',')
<ipython-input-81-024d722643da>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['title'] = data['title'].str.replace(',,',',')
<ipython-input-81-024d722643da>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['title'] = data['title'].str.replace(':','')
<ipython-input-81-024d722643da>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace(' ',',')
<ipython-input-81-024d722643da>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace(',,',',')
<ipython-input-81-024d722643da>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace('_','')
<ipython-input-81-024d722643da>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace(':','')
<ipython-input-81-024d722643da>:10: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['course_description'] = data['course_description'].str.replace('(','')
<ipython-input-81-024d722643da>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace('(','')
<ipython-input-81-024d722643da>:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['course_description'] = data['course_description'].str.replace(')','')
<ipython-input-81-024d722643da>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['course_description'] = data['course_description'].str.replace(')','')
<ipython-input-81-024d722643da>:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['subject'] = data['subject'].str.replace('(','')
<ipython-input-81-024d722643da>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['subject'] = data['subject'].str.replace('(','')
<ipython-input-81-024d722643da>:15: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['subject'] = data['subject'].str.replace(')','')
<ipython-input-81-024d722643da>:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['subject'] = data['subject'].str.replace(')','')

In [82]:
data.head(5)

,title,Level,course_description,subject
0,"How,to,Learn,Online",Introductory,"Designed,for,those,who,are,new,to,elearning,th...",Education & Teacher Training
1,"Programming,for,Everybody,(Getting,Started,wit...",Introductory,"This,course,aims,to,teach,everyone,the,basics,...",Computer Science
2,"CS50's,Introduction,to,Computer,Science",Introductory,"This,is,CS50x,,Harvard,University's,introducti...",Computer Science
3,"The,Analytics,Edge",Intermediate,"In,the,last,decade,the,amount,of,data,availabl...",Data Analysis & Statistics
4,"Marketing,Analytics,Marketing,Measurement,Stra...",Introductory,"Begin,your,journey,in,a,new,career,in,marketin...",Computer Science

# Tags Column

The tags column is the combination of the following columns : **Course Name** + **Difficulty Level** + **Course Description** + **Skills**

In [83]:
data['tags'] = data['title'] + data['subject'] + data['course_description']

<ipython-input-83-95d732b59d24>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tags'] = data['title'] + data['subject'] + data['course_description']

In [84]:
data['tags'].dropna()

0      How,to,Learn,OnlineEducation & Teacher Trainin...
1      Programming,for,Everybody,(Getting,Started,wit...
2      CS50's,Introduction,to,Computer,ScienceCompute...
3      The,Analytics,EdgeData Analysis & StatisticsIn...
4      Marketing,Analytics,Marketing,Measurement,Stra...
                             ...
970    Leaders,in,Citizen,Security,and,Justice,Manage...
971    Pattern,Studying,and,Making,|,图案审美与创作Art & Cul...
972    Computational,Neuroscience,Neuronal,Dynamics,o...
973    Cities,and,the,Challenge,of,Sustainable,Develo...
974    MathTrackX,Special,FunctionsMathThis,course,is...
Name: tags, Length: 935, dtype: object

In [85]:
data.head(5)

,title,Level,course_description,subject,tags
0,"How,to,Learn,Online",Introductory,"Designed,for,those,who,are,new,to,elearning,th...",Education & Teacher Training,"How,to,Learn,OnlineEducation & Teacher Trainin..."
1,"Programming,for,Everybody,(Getting,Started,wit...",Introductory,"This,course,aims,to,teach,everyone,the,basics,...",Computer Science,"Programming,for,Everybody,(Getting,Started,wit..."
2,"CS50's,Introduction,to,Computer,Science",Introductory,"This,is,CS50x,,Harvard,University's,introducti...",Computer Science,"CS50's,Introduction,to,Computer,ScienceCompute..."
3,"The,Analytics,Edge",Intermediate,"In,the,last,decade,the,amount,of,data,availabl...",Data Analysis & Statistics,"The,Analytics,EdgeData Analysis & StatisticsIn..."
4,"Marketing,Analytics,Marketing,Measurement,Stra...",Introductory,"Begin,your,journey,in,a,new,career,in,marketin...",Computer Science,"Marketing,Analytics,Marketing,Measurement,Stra..."

In [86]:
data['tags'].iloc[1]

'Programming,for,Everybody,(Getting,Started,with,Python)Computer ScienceThis,course,aims,to,teach,everyone,the,basics,of,programming,computers,using,Python.,We,cover,the,basics,of,how,one,constructs,a,program,from,a,series,of,simple,instructions,in,Python.,The,course,has,no,pre-requisites,and,avoids,all,but,the,simplest,mathematics.,Anyone,with,moderate,computer,experience,should,be,able,to,master,the,materials,in,this,course.,This,course,will,cover,Chapters,1-5,of,the,textbook,"Python,for,Everybody".,Once,a,student,completes,this,course,they,will,be,ready,to,take,more,advanced,programming,courses.,This,course,covers,Python,3.'

# Dataframe to be used

In [87]:
new_df = data[['title','tags']]

In [88]:
new_df.head(5)

,title,tags
0,"How,to,Learn,Online","How,to,Learn,OnlineEducation & Teacher Trainin..."
1,"Programming,for,Everybody,(Getting,Started,wit...","Programming,for,Everybody,(Getting,Started,wit..."
2,"CS50's,Introduction,to,Computer,Science","CS50's,Introduction,to,Computer,ScienceCompute..."
3,"The,Analytics,Edge","The,Analytics,EdgeData Analysis & StatisticsIn..."
4,"Marketing,Analytics,Marketing,Measurement,Stra...","Marketing,Analytics,Marketing,Measurement,Stra..."

In [89]:
new_df['tags'] = data['tags'].str.replace(',',' ')

<ipython-input-89-afdec3ca82bc>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = data['tags'].str.replace(',',' ')

In [90]:
new_df['title'] = data['title'].str.replace(',',' ')

<ipython-input-90-410b28a0648a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title'] = data['title'].str.replace(',',' ')

In [91]:
new_df.rename(columns = {'title':'title'}, inplace = True)

<ipython-input-91-4a8d6f53c916>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'title':'title'}, inplace = True)

In [92]:
new_df['tags'] = new_df['tags'].str.lower() #lower casing the tags column

<ipython-input-92-8ea9ca88647c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].str.lower() #lower casing the tags column

In [93]:
new_df.head(5)

,title,tags
0,How to Learn Online,how to learn onlineeducation & teacher trainin...
1,Programming for Everybody (Getting Started wit...,programming for everybody (getting started wit...
2,CS50's Introduction to Computer Science,cs50's introduction to computer sciencecompute...
3,The Analytics Edge,the analytics edgedata analysis & statisticsin...
4,Marketing Analytics Marketing Measurement Stra...,marketing analytics marketing measurement stra...
5,Introduction to Project Management,introduction to project managementbusiness & m...
6,Leading High-Performing Teams,leading high-performing teamscommunicationthis...
7,The Foundations of Happiness at Work,the foundations of happiness at workbusiness &...
8,Managing Study Stress and Mental Health at Uni...,managing study stress and mental health at uni...
9,Six Sigma Define and Measure,six sigma define and measurebusiness & managem...
10,Fat Chance Probability from the Ground Up,fat chance probability from the ground upmathc...
11,Chasing your Dream How to End Procrastination ...,chasing your dream how to end procrastination ...
12,Bitcoin and Cryptocurrencies,NaN
13,English Grammar and Style,english grammar and stylehumanitieswith the ri...
14,Ethics in Action,ethics in actionethicsthe challenges of sustai...
15,Introduction to FinTech,introduction to fintecheconomics & finance ove...
16,Data Science R Basics,data science r basicsdata analysis & statistic...
17,Python Basics for Data Science,python basics for data sciencedata analysis & ...
18,The Science of Beer,the science of beerfood & nutrition have you e...
19,Strategic Social Media Marketing,strategic social media marketingbusiness & man...
20,CS50's Introduction to Artificial Intelligence...,cs50's introduction to artificial intelligence...
21,CS50's Introduction to Game Development,NaN
22,Rhetoric The Art of Persuasive Writing and Pub...,rhetoric the art of persuasive writing and pub...
23,CS50's Web Programming with Python and JavaScript,cs50's web programming with python and javascr...
24,Contract Law From Trust to Promise to Contract,contract law from trust to promise to contract...
25,Fundamentals of Neuroscience Part 1 The Electr...,fundamentals of neuroscience part 1 the electr...
26,Justice,justicehumanitiestaught by lauded harvard prof...
27,Data Science Machine Learning,data science machine learningdata analysis & s...
28,Child Protection Children's Rights in Theory a...,child protection children's rights in theory a...
29,IELTS Academic Test Preparation,ielts academic test preparationcommunicationie...

In [94]:
new_df = new_df[new_df['tags'].notnull()]

In [95]:
new_df.shape #3522 courses with tags and 2 columns (course_name and tags)

(935, 2)

In [96]:
new_df.fillna('')

,title,tags
0,How to Learn Online,how to learn onlineeducation & teacher trainin...
1,Programming for Everybody (Getting Started wit...,programming for everybody (getting started wit...
2,CS50's Introduction to Computer Science,cs50's introduction to computer sciencecompute...
3,The Analytics Edge,the analytics edgedata analysis & statisticsin...
4,Marketing Analytics Marketing Measurement Stra...,marketing analytics marketing measurement stra...
...,...,...
970,Leaders in Citizen Security and Justice Manage...,leaders in citizen security and justice manage...
971,Pattern Studying and Making | 图案审美与创作,pattern studying and making | 图案审美与创作art & cul...
972,Computational Neuroscience Neuronal Dynamics o...,computational neuroscience neuronal dynamics o...
973,Cities and the Challenge of Sustainable Develo...,cities and the challenge of sustainable develo...
974,MathTrackX Special Functions,mathtrackx special functionsmaththis course is...

# Text Vectorization

In [97]:
from sklearn.feature_extraction.text import CountVectorizer

In [98]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [99]:
vectors = cv.fit_transform(new_df['tags']).toarray()

# Stemming Process

In [100]:
import nltk #for stemming process

In [101]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [102]:
#defining the stemming function
def stem(text):
    y=[]
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [103]:
new_df['tags'] = new_df['tags'].apply(stem) #applying stemming on the tags column

# Similarity Measure

In [104]:
from sklearn.metrics.pairwise import cosine_similarity

In [105]:
similarity = cosine_similarity(vectors)

# Recommendation Function

In [106]:
def recommend(course):
    course_index = new_df[new_df['title'] == course].index[0]
    distances = similarity[course_index]
    course_list = sorted(list(enumerate(distances)),reverse=True, key=lambda x:x[1])[10:20]
    
    for i in course_list:
        print(new_df.iloc[i[0]].title)

In [107]:
recommend('The Analytics Edge')

Visualizing Data with Python
Programming for Data Science
Big Data Analytics
Statistics and R
Data Science for Construction Architecture and Engineering
Data Science Wrangling
Big Data Fundamentals
Data Analysis Essentials
Data for Effective Policy Making
Enabling Technologies for Data Science and Analytics The Internet of Things

**So these are the 10 courses which are recommended based on our search in the recommendation function**